### ISSUE TITLE
Single user setup

### ISSUE THREAD

**Issue by lioman** [frenya/vscode-coffeebreak-todoist#2]
Even if you are the only person, you have to mention your self very often.
A single user option that all tasks are synced as personal tasks would be nice.

**Comment by frenya** [comment]
Hi. This is currently doable by adding an "<unassigned>" mention in the configuration (either at workspace or folder level), e.g.

```json
...
  "coffeebreak.mentions": {
    "<unassigned>": {
      "email": "frenya@frenya.net"
    },
  }
...
```

Once you add this, all the unassigned tasks will be considered yours and should sync to Todoist. Needless to say, instead of frenya@frenya.net you need to use one of the addresses listed in `"coffeebreak.emails"` configuration. More details on the logic can be found in https://meetcoffeebreak.net/collaboration

I will update to documentation to include the above mentioned.

Let me know if it worked ...

**Comment by lioman** [comment]
Thanks it worked

**Comment by frenya** [comment]
Documentation updated. Closing the issue.
